import React from 'react';

const quotes = [
  "The best way to get started is to quit talking and begin doing. – Walt Disney",
  "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. – Winston Churchill",
  "Don’t let yesterday take up too much of today. – Will Rogers",
  "You learn more from failure than from success. Don’t let it stop you. Failure builds character. – Unknown",
  "It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi",
  "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you. – Steve Jobs",
  "People who are crazy enough to think they can change the world, are the ones who do. – Rob Siltanen",
  "Failure will never overtake me if my determination to succeed is strong enough. – Og Mandino",
  "Entrepreneurs are great at dealing with uncertainty and also very good at minimizing risk. That’s the classic entrepreneur. – Mohnish Pabrai",
  "We may encounter many defeats but we must not be defeated. – Maya Angelou",
  "Knowing is not enough; we must apply. Wishing is not enough; we must do. – Johann Wolfgang Von Goethe",
  "Imagine your life is perfect in every respect; what would it look like? – Brian Tracy",
  "We generate fears while we sit. We overcome them by action. – Dr. Henry Link",
  "Whether you think you can or think you can’t, you’re right. – Henry Ford",
  "Security is mostly a superstition. Life is either a daring adventure or nothing. – Helen Keller",
  "The man who has confidence in himself gains the confidence of others. – Hasidic Proverb",
  "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
  "Creativity is intelligence having fun. – Albert Einstein",
  "What you lack in talent can be made up with desire, hustle and giving 110% all the time. – Don Zimmer",
  "Do what you can with all you have, wherever you are. – Theodore Roosevelt",
  "Develop an ‘Attitude of Gratitude’. Say thank you to everyone you meet for everything they do for you. – Brian Tracy",
  "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
  "To see what is right and not do it is a lack of courage. – Confucius",
  "Reading is to the mind, as exercise is to the body. – Brian Tracy",
  "Fake it until you make it! Act as if you had all the confidence you require until it becomes your reality. – Brian Tracy",
  "The future belongs to the competent. Get good, get better, be the best! – Brian Tracy",
  "For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded. – Jack Canfield",
  "Things work out best for those who make the best of how things work out. – John Wooden",
  "A room without books is like a body without a soul. – Marcus Tullius Cicero",
  "I think goals should never be easy, they should force you to work, even if they are uncomfortable at the time. – Michael Phelps",
  "One of the lessons that I grew up with was to always stay true to yourself and never let what somebody else says distract you from your goals. – Michelle Obama",
  "Today’s accomplishments were yesterday’s impossibilities. – Robert H. Schuller",
  "The only way to do great work is to love what you do. – Steve Jobs",
  "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. – Albert Schweitzer",
  "Success seems to be connected with action. Successful people keep moving. They make mistakes but they don’t quit. – Conrad Hilton",
  "Successful people do what unsuccessful people are not willing to do. Don’t wish it were easier, wish you were better. – Jim Rohn",
  "If you are not willing to risk the usual, you will have to settle for the ordinary. – Jim Rohn",
  "The ones who are crazy enough to think they can change the world, are the ones that do. – Anonymous",
  "Good things come to people who wait, but better things come to those who go out and get them. – Anonymous",
  "If you do what you always did, you will get what you always got. – Anonymous",
  "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
  "Just when the caterpillar thought the world was ending, he turned into a butterfly. – Proverb",
  "Successful entrepreneurs are givers and not takers of positive energy. – Anonymous",
  "Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them. – Vaibhav Shah",
  "Opportunities don’t happen, you create them. – Chris Grosser",
  "Try not to become a person of success, but rather try to become a person of value. – Albert Einstein",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people. – Eleanor Roosevelt",
  "I have not failed. I’ve just found 10,000 ways that won’t work. – Thomas A. Edison",
  "If you don’t value your time, neither will others. Stop giving away your time and talents–start charging for it. – Kim Garst",
  "A successful man is one who can lay a firm foundation with the bricks others have thrown at him. – David Brinkley",
  "No one can make you feel inferior without your consent. – Eleanor Roosevelt",
  "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it. – Henry Ford",
  "If you’re going through hell keep going. – Winston Churchill",
  "The ones who are crazy enough to think they can change the world, are the ones that do. – Steve Jobs",
  "Don’t raise your voice, improve your argument. – Anonymous",
  "What seems to us as bitter trials are often blessings in disguise. – Oscar Wilde",
  "The meaning of life is to find your gift. The purpose of life is to give it away. – Anonymous",
  "The distance between insanity and genius is measured only by success. – Bruce Feirstein",
  "When you stop chasing the wrong things, you give the right things a chance to catch you. – Lolly Daskal",
  "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller",
  "No masterpiece was ever created by a lazy artist. – Anonymous",
  "Happiness is not something readymade. It comes from your own actions. – Dalai Lama",
  "If you can’t explain it simply, you don’t understand it well enough. – Albert Einstein",
  "Blessed are those who can give without remembering and take without forgetting. – Anonymous",
  "Do one thing every day that scares you. – Anonymous",
  "What’s the point of being alive if you don’t at least try to do something remarkable. – Anonymous",
  "Life is not about finding yourself. Life is about creating yourself. – Lolly Daskal",
  "Nothing in the world is more common than unsuccessful people with talent. – Anonymous",
  "Knowledge is being aware of what you can do. Wisdom is knowing when not to do it. – Anonymous",
  "Your problem isn’t the problem. Your reaction is the problem. – Anonymous",
  "You can do anything, but not everything. – Anonymous",
  "Innovation distinguishes between a leader and a follower. – Steve Jobs",
  "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed. – Ray Goforth",
  "Thinking should become your capital asset, no matter whatever ups and downs you come across in your life. – Dr. APJ Kalam",
  "I find that the harder I work, the more luck I seem to have. – Thomas Jefferson",
  "The starting point of all achievement is desire. – Napoleon Hill",
  "Success is the sum of small efforts, repeated day-in and day-out. – Robert Collier",
  "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work. – Thomas J. Watson",
  "All progress takes place outside the comfort zone. – Michael John Bobak",
  "You may only succeed if you desire succeeding; you may only fail if you do not mind failing. – Philippos",
  "Courage is resistance to fear, mastery of fear–not absence of fear. – Mark Twain",
  "Only put off until tomorrow what you are willing to die having left undone. – Pablo Picasso",
  "People often say that motivation doesn’t last. Well, neither does bathing–that’s why we recommend it daily. – Zig Ziglar",
  "We become what we think about most of the time, and that’s the strangest secret. – Earl Nightingale",
  "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
  "Too many of us are not living our dreams because we are living our fears. – Les Brown",
  "I find that when you have a real interest in life and a curious life, that sleep is not the most important thing. – Martha Stewart",
  "It’s not what you look at that matters, it’s what you see. – Anonymous",
  "The road to success and the road to failure are almost exactly the same. – Colin R. Davis",
  "The function of leadership is to produce more leaders, not more followers. – Ralph Nader",
  "Success is liking yourself, liking what you do, and liking how you do it. – Maya Angelou",
  "As we look ahead into the next century, leaders will be those who empower others. – Bill Gates",
  "A real entrepreneur is somebody who has no safety net underneath them. – Henry Kravis",
  "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself. – Mark Caine"
];

const Quotes = () => {
  const today = new Date();
  const dayOfYear = Math.floor((today - new Date(today.getFullYear(), 0, 0)) / 1000 / 60 / 60 / 24);
  const quoteOfTheDay = quotes[dayOfYear % quotes.length];

  return (
    <div className="container mx-auto p-4">
      <h1 className="text-4xl font-bold">Inspirational Quote of the Day</h1>
      <p className="mt-4">{quoteOfTheDay}</p>
    </div>
  );
};

export default Quotes;
